"""updated table schema

Revision ID: 593ccbf25b61
Revises: 9e1de5593bd7
Create Date: 2023-04-20 12:37:02.437440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593ccbf25b61'
down_revision = '9e1de5593bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retreats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_retreats_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retreats'))
    )
    op.create_table('petRetreats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('retreat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['saved_pets.id'], name=op.f('fk_petRetreats_pet_id_saved_pets')),
    sa.ForeignKeyConstraint(['retreat_id'], ['retreats.id'], name=op.f('fk_petRetreats_retreat_id_retreats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_petRetreats'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petRetreats')
    op.drop_table('retreats')
    # ### end Alembic commands ###
