"""Adds petfinder_id to saved_pets

Revision ID: ef8ad8f151da
Revises: 8b93c7aa8904
Create Date: 2023-04-18 13:12:23.144644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8ad8f151da'
down_revision = '8b93c7aa8904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petfinder_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_pets', schema=None) as batch_op:
        batch_op.drop_column('petfinder_id')

    # ### end Alembic commands ###
